//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/hub_type.proto

//go:build protoopaque

package privatev1

import (
	_ "github.com/osac-project/osac/osac-operator/internal/dummy/cleanapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains the details of a hub.
type Hub struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *HubSpec               `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *HubStatus             `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Hub) Reset() {
	*x = Hub{}
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hub) ProtoMessage() {}

func (x *Hub) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hub) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Hub) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Hub) GetSpec() *HubSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Hub) GetStatus() *HubStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Hub) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Hub) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Hub) SetSpec(v *HubSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Hub) SetStatus(v *HubStatus) {
	x.xxx_hidden_Status = v
}

func (x *Hub) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Hub) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Hub) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Hub) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Hub) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Hub) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Hub_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the hub.
	//
	// This will be automatically generated by the server when the hub is created.
	Id string
	// Metadata of the hub.
	Metadata *Metadata
	// Desired and current state of the hub.
	Spec   *HubSpec
	Status *HubStatus
}

func (b0 Hub_builder) Build() *Hub {
	m0 := &Hub{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// Desired state of the hub.
type HubSpec struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kubeconfig       []byte                 `protobuf:"bytes,3,opt,name=kubeconfig,proto3"`
	xxx_hidden_Namespace        string                 `protobuf:"bytes,4,opt,name=namespace,proto3"`
	xxx_hidden_KubeconfigSecret *SecretLocalReference  `protobuf:"bytes,5,opt,name=kubeconfig_secret,json=kubeconfigSecret,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *HubSpec) Reset() {
	*x = HubSpec{}
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubSpec) ProtoMessage() {}

func (x *HubSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HubSpec) GetKubeconfig() []byte {
	if x != nil {
		return x.xxx_hidden_Kubeconfig
	}
	return nil
}

func (x *HubSpec) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *HubSpec) GetKubeconfigSecret() *SecretLocalReference {
	if x != nil {
		return x.xxx_hidden_KubeconfigSecret
	}
	return nil
}

func (x *HubSpec) SetKubeconfig(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kubeconfig = v
}

func (x *HubSpec) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

func (x *HubSpec) SetKubeconfigSecret(v *SecretLocalReference) {
	x.xxx_hidden_KubeconfigSecret = v
}

func (x *HubSpec) HasKubeconfigSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KubeconfigSecret != nil
}

func (x *HubSpec) ClearKubeconfigSecret() {
	x.xxx_hidden_KubeconfigSecret = nil
}

type HubSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Kubeconfig containing the address and credentials that the service will use to connect to the hub.
	//
	// Mutually exclusive with `kubeconfig_secret`.
	Kubeconfig []byte
	// Namespace where the cluster orders will be created.
	Namespace string
	// Reference to a Secret resource containing kubeconfig credentials.
	//
	// Mutually exclusive with `kubeconfig`. When set, the system resolves the referenced Secret and reads the
	// `kubeconfig` data key. The referenced Secret must exist in the same tenant.
	KubeconfigSecret *SecretLocalReference
}

func (b0 HubSpec_builder) Build() *HubSpec {
	m0 := &HubSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Kubeconfig = b.Kubeconfig
	x.xxx_hidden_Namespace = b.Namespace
	x.xxx_hidden_KubeconfigSecret = b.KubeconfigSecret
	return m0
}

// Current state of the hub.
type HubStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubStatus) Reset() {
	*x = HubStatus{}
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubStatus) ProtoMessage() {}

func (x *HubStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_hub_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HubStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HubStatus_builder) Build() *HubStatus {
	m0 := &HubStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_hub_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_hub_type_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x68, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x17, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x65, 0x61,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x21, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x03, 0x48, 0x75, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2c, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x75, 0x62, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12,
	0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x07, 0x48, 0x75, 0x62, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x1e, 0x0a, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x52, 0x0a,
	0x11, 0x6b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x10, 0x6b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0xdc,
	0x01, 0x8a, 0xb5, 0x18, 0x02, 0x08, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x48, 0x75,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x51, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61,
	0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63,
	0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_hub_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_hub_type_proto_goTypes = []any{
	(*Hub)(nil),                  // 0: osac.private.v1.Hub
	(*HubSpec)(nil),              // 1: osac.private.v1.HubSpec
	(*HubStatus)(nil),            // 2: osac.private.v1.HubStatus
	(*Metadata)(nil),             // 3: osac.private.v1.Metadata
	(*SecretLocalReference)(nil), // 4: osac.private.v1.SecretLocalReference
}
var file_osac_private_v1_hub_type_proto_depIdxs = []int32{
	3, // 0: osac.private.v1.Hub.metadata:type_name -> osac.private.v1.Metadata
	1, // 1: osac.private.v1.Hub.spec:type_name -> osac.private.v1.HubSpec
	2, // 2: osac.private.v1.Hub.status:type_name -> osac.private.v1.HubStatus
	4, // 3: osac.private.v1.HubSpec.kubeconfig_secret:type_name -> osac.private.v1.SecretLocalReference
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_hub_type_proto_init() }
func file_osac_private_v1_hub_type_proto_init() {
	if File_osac_private_v1_hub_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_secret_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_hub_type_proto_rawDesc), len(file_osac_private_v1_hub_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_hub_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_hub_type_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_hub_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_hub_type_proto = out.File
	file_osac_private_v1_hub_type_proto_goTypes = nil
	file_osac_private_v1_hub_type_proto_depIdxs = nil
}
