//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/storage_backend_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/osac-project/osac/osac-operator/internal/api/cleanapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for StorageBackend resources.
type StorageBackendState int32

const (
	// State is unknown or has not been determined yet.
	StorageBackendState_STORAGE_BACKEND_STATE_UNSPECIFIED StorageBackendState = 0
	// The storage backend is registered and available.
	StorageBackendState_STORAGE_BACKEND_STATE_READY StorageBackendState = 1
)

// Enum value maps for StorageBackendState.
var (
	StorageBackendState_name = map[int32]string{
		0: "STORAGE_BACKEND_STATE_UNSPECIFIED",
		1: "STORAGE_BACKEND_STATE_READY",
	}
	StorageBackendState_value = map[string]int32{
		"STORAGE_BACKEND_STATE_UNSPECIFIED": 0,
		"STORAGE_BACKEND_STATE_READY":       1,
	}
)

func (x StorageBackendState) Enum() *StorageBackendState {
	p := new(StorageBackendState)
	*p = x
	return p
}

func (x StorageBackendState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackendState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_storage_backend_type_proto_enumTypes[0].Descriptor()
}

func (StorageBackendState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_storage_backend_type_proto_enumTypes[0]
}

func (x StorageBackendState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a registered storage backend in the OSAC platform.
//
// StorageBackend is a platform-scoped entity that stores the provider type, management endpoint, and credentials for
// a storage array. It is managed exclusively by Cloud Provider Admins through the private API. Tenants do not have
// direct access to storage backends; they interact with storage through StorageTier (OSAC-1110).
//
// StorageBackend follows the NetworkClass pattern: DB-backed with no Kubernetes CRD and no reconciler.
type StorageBackend struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the storage backend.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the storage backend.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the storage backend (user-modifiable).
	Spec *StorageBackendSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current operational status of the storage backend.
	Status        *StorageBackendStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageBackend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorageBackend) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StorageBackend) GetSpec() *StorageBackendSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *StorageBackend) GetStatus() *StorageBackendStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StorageBackend) SetId(v string) {
	x.Id = v
}

func (x *StorageBackend) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *StorageBackend) SetSpec(v *StorageBackendSpec) {
	x.Spec = v
}

func (x *StorageBackend) SetStatus(v *StorageBackendStatus) {
	x.Status = v
}

func (x *StorageBackend) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *StorageBackend) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *StorageBackend) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *StorageBackend) ClearMetadata() {
	x.Metadata = nil
}

func (x *StorageBackend) ClearSpec() {
	x.Spec = nil
}

func (x *StorageBackend) ClearStatus() {
	x.Status = nil
}

type StorageBackend_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the storage backend.
	Id string
	// Metadata of the storage backend.
	Metadata *Metadata
	// Desired configuration of the storage backend (user-modifiable).
	Spec *StorageBackendSpec
	// Current operational status of the storage backend.
	Status *StorageBackendStatus
}

func (b0 StorageBackend_builder) Build() *StorageBackend {
	m0 := &StorageBackend{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the desired configuration for a StorageBackend.
type StorageBackendSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Storage provider identifier. For example: "vast", "ceph", "pure".
	//
	// This value is immutable once the StorageBackend is created.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Human-readable description of the storage backend.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Management endpoint for the storage array. Accepts a URL or host:port format.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Credentials for authenticating with the storage management API.
	Credentials   *StorageBackendCredentials `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackendSpec) Reset() {
	*x = StorageBackendSpec{}
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackendSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackendSpec) ProtoMessage() {}

func (x *StorageBackendSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageBackendSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StorageBackendSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StorageBackendSpec) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StorageBackendSpec) GetCredentials() *StorageBackendCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *StorageBackendSpec) SetProvider(v string) {
	x.Provider = v
}

func (x *StorageBackendSpec) SetDescription(v string) {
	x.Description = v
}

func (x *StorageBackendSpec) SetEndpoint(v string) {
	x.Endpoint = v
}

func (x *StorageBackendSpec) SetCredentials(v *StorageBackendCredentials) {
	x.Credentials = v
}

func (x *StorageBackendSpec) HasCredentials() bool {
	if x == nil {
		return false
	}
	return x.Credentials != nil
}

func (x *StorageBackendSpec) ClearCredentials() {
	x.Credentials = nil
}

type StorageBackendSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Storage provider identifier. For example: "vast", "ceph", "pure".
	//
	// This value is immutable once the StorageBackend is created.
	Provider string
	// Human-readable description of the storage backend.
	Description string
	// Management endpoint for the storage array. Accepts a URL or host:port format.
	Endpoint string
	// Credentials for authenticating with the storage management API.
	Credentials *StorageBackendCredentials
}

func (b0 StorageBackendSpec_builder) Build() *StorageBackendSpec {
	m0 := &StorageBackendSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Provider = b.Provider
	x.Description = b.Description
	x.Endpoint = b.Endpoint
	x.Credentials = b.Credentials
	return m0
}

// Credentials for authenticating with a storage backend's management API.
type StorageBackendCredentials struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Username for storage management API authentication.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password for storage management API authentication.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackendCredentials) Reset() {
	*x = StorageBackendCredentials{}
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackendCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackendCredentials) ProtoMessage() {}

func (x *StorageBackendCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageBackendCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StorageBackendCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *StorageBackendCredentials) SetUsername(v string) {
	x.Username = v
}

func (x *StorageBackendCredentials) SetPassword(v string) {
	x.Password = v
}

type StorageBackendCredentials_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Username for storage management API authentication.
	Username string
	// Password for storage management API authentication.
	Password string
}

func (b0 StorageBackendCredentials_builder) Build() *StorageBackendCredentials {
	m0 := &StorageBackendCredentials{}
	b, x := &b0, m0
	_, _ = b, x
	x.Username = b.Username
	x.Password = b.Password
	return m0
}

// Represents the current operational state of a StorageBackend.
type StorageBackendStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the storage backend.
	State StorageBackendState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.StorageBackendState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackendStatus) Reset() {
	*x = StorageBackendStatus{}
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackendStatus) ProtoMessage() {}

func (x *StorageBackendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_storage_backend_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageBackendStatus) GetState() StorageBackendState {
	if x != nil {
		return x.State
	}
	return StorageBackendState_STORAGE_BACKEND_STATE_UNSPECIFIED
}

func (x *StorageBackendStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *StorageBackendStatus) SetState(v StorageBackendState) {
	x.State = v
}

func (x *StorageBackendStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *StorageBackendStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *StorageBackendStatus) ClearMessage() {
	x.Message = nil
}

type StorageBackendStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the storage backend.
	State StorageBackendState
	// Human-readable message providing additional details about the current state.
	Message *string
}

func (b0 StorageBackendStatus_builder) Build() *StorageBackendStatus {
	m0 := &StorageBackendStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_private_v1_storage_backend_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_storage_backend_type_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6c, 0x65, 0x61,
	0x6e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x3f, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x53, 0x70, 0x65, 0x63, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xd6, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x23, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x23, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x54, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x65, 0x0a, 0x19, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x7d, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0x5d, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x53, 0x54, 0x4f, 0x52,
	0x41, 0x47, 0x45, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x45, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1f, 0x0a, 0x1b, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x45,
	0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x01,
	0x42, 0xe7, 0x01, 0x8a, 0xb5, 0x18, 0x02, 0x08, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x17,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f,
	0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var file_osac_private_v1_storage_backend_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_storage_backend_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_storage_backend_type_proto_goTypes = []any{
	(StorageBackendState)(0),          // 0: osac.private.v1.StorageBackendState
	(*StorageBackend)(nil),            // 1: osac.private.v1.StorageBackend
	(*StorageBackendSpec)(nil),        // 2: osac.private.v1.StorageBackendSpec
	(*StorageBackendCredentials)(nil), // 3: osac.private.v1.StorageBackendCredentials
	(*StorageBackendStatus)(nil),      // 4: osac.private.v1.StorageBackendStatus
	(*Metadata)(nil),                  // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_storage_backend_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.StorageBackend.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.StorageBackend.spec:type_name -> osac.private.v1.StorageBackendSpec
	4, // 2: osac.private.v1.StorageBackend.status:type_name -> osac.private.v1.StorageBackendStatus
	3, // 3: osac.private.v1.StorageBackendSpec.credentials:type_name -> osac.private.v1.StorageBackendCredentials
	0, // 4: osac.private.v1.StorageBackendStatus.state:type_name -> osac.private.v1.StorageBackendState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_storage_backend_type_proto_init() }
func file_osac_private_v1_storage_backend_type_proto_init() {
	if File_osac_private_v1_storage_backend_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_storage_backend_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_storage_backend_type_proto_rawDesc), len(file_osac_private_v1_storage_backend_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_storage_backend_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_storage_backend_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_storage_backend_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_storage_backend_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_storage_backend_type_proto = out.File
	file_osac_private_v1_storage_backend_type_proto_goTypes = nil
	file_osac_private_v1_storage_backend_type_proto_depIdxs = nil
}
