{{- if .Values.lvms.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "osac-deps.labels" . | nindent 4 }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator
  namespace: openshift-storage
  labels:
    {{- include "osac-deps.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms-operator
  namespace: openshift-storage
  labels:
    {{- include "osac-deps.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.lvms.channel }}
  name: lvms-operator
  source: {{ .Values.catalogSource }}
  sourceNamespace: {{ .Values.catalogSourceNamespace }}
  installPlanApproval: Automatic
{{- end }}
