{{- if .Values.mce.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: multicluster-engine
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "osac-deps.labels" . | nindent 4 }}
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mce
  namespace: multicluster-engine
  labels:
    {{- include "osac-deps.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - multicluster-engine
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: multicluster-engine
  labels:
    {{- include "osac-deps.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.mce.channel }}
  name: multicluster-engine
  source: {{ .Values.catalogSource }}
  sourceNamespace: {{ .Values.catalogSourceNamespace }}
  installPlanApproval: Automatic
{{- end }}
