//
//Copyright (c) 2026 Red Hat, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
//the License. You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
//an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
//specific language governing permissions and limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: cleanapi/cleanapi.proto

//go:build !protoopaque

package cleanapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks a file as private, so that it will be excluded from the public API.
	Private bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	// Indicates that the package name should be replaced by this.
	Package string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	// When true, removes google.api.http annotations used for gRPC-to-REST transcoding.
	RemoveHttpOptions bool `protobuf:"varint,3,opt,name=remove_http_options,json=removeHttpOptions,proto3" json:"remove_http_options,omitempty"`
	// Specifies HTTP route prefix remapping in the format "old_prefix:new_prefix".
	// For example, "old:new" will rewrite all routes from "/api/old/*" to "/api/new/*".
	// The replacement is done on the first occurrence of the old prefix in the route path.
	HttpRoutePrefixMap string `protobuf:"bytes,4,opt,name=http_route_prefix_map,json=httpRoutePrefixMap,proto3" json:"http_route_prefix_map,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *FileOptions) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *FileOptions) GetRemoveHttpOptions() bool {
	if x != nil {
		return x.RemoveHttpOptions
	}
	return false
}

func (x *FileOptions) GetHttpRoutePrefixMap() string {
	if x != nil {
		return x.HttpRoutePrefixMap
	}
	return ""
}

func (x *FileOptions) SetPrivate(v bool) {
	x.Private = v
}

func (x *FileOptions) SetPackage(v string) {
	x.Package = v
}

func (x *FileOptions) SetRemoveHttpOptions(v bool) {
	x.RemoveHttpOptions = v
}

func (x *FileOptions) SetHttpRoutePrefixMap(v string) {
	x.HttpRoutePrefixMap = v
}

type FileOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks a file as private, so that it will be excluded from the public API.
	Private bool
	// Indicates that the package name should be replaced by this.
	Package string
	// When true, removes google.api.http annotations used for gRPC-to-REST transcoding.
	RemoveHttpOptions bool
	// Specifies HTTP route prefix remapping in the format "old_prefix:new_prefix".
	// For example, "old:new" will rewrite all routes from "/api/old/*" to "/api/new/*".
	// The replacement is done on the first occurrence of the old prefix in the route path.
	HttpRoutePrefixMap string
}

func (b0 FileOptions_builder) Build() *FileOptions {
	m0 := &FileOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	x.Package = b.Package
	x.RemoveHttpOptions = b.RemoveHttpOptions
	x.HttpRoutePrefixMap = b.HttpRoutePrefixMap
	return m0
}

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks a message as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *MessageOptions) SetPrivate(v bool) {
	x.Private = v
}

type MessageOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks a message as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 MessageOptions_builder) Build() *MessageOptions {
	m0 := &MessageOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks a field as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *FieldOptions) SetPrivate(v bool) {
	x.Private = v
}

type FieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks a field as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 FieldOptions_builder) Build() *FieldOptions {
	m0 := &FieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

type EnumOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks an enum as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnumOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *EnumOptions) SetPrivate(v bool) {
	x.Private = v
}

type EnumOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks an enum as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 EnumOptions_builder) Build() *EnumOptions {
	m0 := &EnumOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks an enum value as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnumValueOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *EnumValueOptions) SetPrivate(v bool) {
	x.Private = v
}

type EnumValueOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks an enum value as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 EnumValueOptions_builder) Build() *EnumValueOptions {
	m0 := &EnumValueOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Marks a service as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *ServiceOptions) SetPrivate(v bool) {
	x.Private = v
}

type ServiceOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Marks a service as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 ServiceOptions_builder) Build() *ServiceOptions {
	m0 := &ServiceOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

type MethodOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Mars a field as private, so that it will be excluded from the public API.
	Private       bool `protobuf:"varint,1,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_cleanapi_cleanapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cleanapi_cleanapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MethodOptions) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *MethodOptions) SetPrivate(v bool) {
	x.Private = v
}

type MethodOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Mars a field as private, so that it will be excluded from the public API.
	Private bool
}

func (b0 MethodOptions_builder) Build() *MethodOptions {
	m0 := &MethodOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Private = b.Private
	return m0
}

var file_cleanapi_cleanapi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.file",
		Tag:           "bytes,50001,opt,name=file",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.message",
		Tag:           "bytes,50001,opt,name=message",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.field",
		Tag:           "bytes,50001,opt,name=field",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.enum",
		Tag:           "bytes,50001,opt,name=enum",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.value",
		Tag:           "bytes,50001,opt,name=value",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.service",
		Tag:           "bytes,50001,opt,name=service",
		Filename:      "cleanapi/cleanapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         50001,
		Name:          "cleanapi.method",
		Tag:           "bytes,50001,opt,name=method",
		Filename:      "cleanapi/cleanapi.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional cleanapi.FileOptions file = 50001;
	E_File = &file_cleanapi_cleanapi_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional cleanapi.MessageOptions message = 50001;
	E_Message = &file_cleanapi_cleanapi_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional cleanapi.FieldOptions field = 50001;
	E_Field = &file_cleanapi_cleanapi_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional cleanapi.EnumOptions enum = 50001;
	E_Enum = &file_cleanapi_cleanapi_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional cleanapi.EnumValueOptions value = 50001;
	E_Value = &file_cleanapi_cleanapi_proto_extTypes[4]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional cleanapi.ServiceOptions service = 50001;
	E_Service = &file_cleanapi_cleanapi_proto_extTypes[5]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional cleanapi.MethodOptions method = 50001;
	E_Method = &file_cleanapi_cleanapi_proto_extTypes[6]
)

var File_cleanapi_cleanapi_proto protoreflect.FileDescriptor

var file_cleanapi_cleanapi_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6c, 0x65, 0x61, 0x6e,
	0x61, 0x70, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x74,
	0x74, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x68, 0x74, 0x74,
	0x70, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6d,
	0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x68, 0x74, 0x74, 0x70, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4d, 0x61, 0x70, 0x22, 0x2a, 0x0a, 0x0e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x45,
	0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x3a, 0x49, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x3a, 0x55, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x3a, 0x4d, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x3a, 0x49, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x3a, 0x55, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x55, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x51, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x42, 0xa1, 0x01,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x42, 0x0d,
	0x43, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x6f, 0x73,
	0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x6e,
	0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x61, 0x70, 0x69, 0xca, 0x02, 0x08, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0xe2,
	0x02, 0x14, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70, 0x69, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_cleanapi_cleanapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cleanapi_cleanapi_proto_goTypes = []any{
	(*FileOptions)(nil),                   // 0: cleanapi.FileOptions
	(*MessageOptions)(nil),                // 1: cleanapi.MessageOptions
	(*FieldOptions)(nil),                  // 2: cleanapi.FieldOptions
	(*EnumOptions)(nil),                   // 3: cleanapi.EnumOptions
	(*EnumValueOptions)(nil),              // 4: cleanapi.EnumValueOptions
	(*ServiceOptions)(nil),                // 5: cleanapi.ServiceOptions
	(*MethodOptions)(nil),                 // 6: cleanapi.MethodOptions
	(*descriptorpb.FileOptions)(nil),      // 7: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 8: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 9: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),      // 10: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 11: google.protobuf.EnumValueOptions
	(*descriptorpb.ServiceOptions)(nil),   // 12: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 13: google.protobuf.MethodOptions
}
var file_cleanapi_cleanapi_proto_depIdxs = []int32{
	7,  // 0: cleanapi.file:extendee -> google.protobuf.FileOptions
	8,  // 1: cleanapi.message:extendee -> google.protobuf.MessageOptions
	9,  // 2: cleanapi.field:extendee -> google.protobuf.FieldOptions
	10, // 3: cleanapi.enum:extendee -> google.protobuf.EnumOptions
	11, // 4: cleanapi.value:extendee -> google.protobuf.EnumValueOptions
	12, // 5: cleanapi.service:extendee -> google.protobuf.ServiceOptions
	13, // 6: cleanapi.method:extendee -> google.protobuf.MethodOptions
	0,  // 7: cleanapi.file:type_name -> cleanapi.FileOptions
	1,  // 8: cleanapi.message:type_name -> cleanapi.MessageOptions
	2,  // 9: cleanapi.field:type_name -> cleanapi.FieldOptions
	3,  // 10: cleanapi.enum:type_name -> cleanapi.EnumOptions
	4,  // 11: cleanapi.value:type_name -> cleanapi.EnumValueOptions
	5,  // 12: cleanapi.service:type_name -> cleanapi.ServiceOptions
	6,  // 13: cleanapi.method:type_name -> cleanapi.MethodOptions
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	7,  // [7:14] is the sub-list for extension type_name
	0,  // [0:7] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cleanapi_cleanapi_proto_init() }
func file_cleanapi_cleanapi_proto_init() {
	if File_cleanapi_cleanapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cleanapi_cleanapi_proto_rawDesc), len(file_cleanapi_cleanapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_cleanapi_cleanapi_proto_goTypes,
		DependencyIndexes: file_cleanapi_cleanapi_proto_depIdxs,
		MessageInfos:      file_cleanapi_cleanapi_proto_msgTypes,
		ExtensionInfos:    file_cleanapi_cleanapi_proto_extTypes,
	}.Build()
	File_cleanapi_cleanapi_proto = out.File
	file_cleanapi_cleanapi_proto_goTypes = nil
	file_cleanapi_cleanapi_proto_depIdxs = nil
}
